import os
from fastapi.middleware.cors import CORSMiddleware

# Get CORS origins from environment variable
cors_origins_str = os.getenv(
    "CORS_ORIGINS",
    "http://localhost:3000"
)

# Split the comma-separated string into a list
allowed_origins = [origin.strip() for origin in cors_origins_str.split(",")]

# Add the specific Vercel preview URL explicitly
allowed_origins.append("https://indian-legal-ai-frontend-y8gem6i2w-ashus-projects-918909e4.vercel.app")

# Remove duplicates
allowed_origins = list(set(allowed_origins))

app.add_middleware(
    CORSMiddleware,
    allow_origins=allowed_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Pydantic models
class ChatRequest(BaseModel):
    message: str

class SearchRequest(BaseModel):
    query: str

class DocumentRequest(BaseModel):
    document_type: str
    details: str

# Root endpoint
@app.get("/")
def root():
    return {"message": "Indian Legal AI API", "status": "running"}

# Health check
@app.get("/health")
def health():
    return {"status": "healthy", "version": "1.0.0"}

# Test endpoint
@app.get("/api/test")
def test():
    return {"message": "API is working!"}

# Chat endpoint
@app.post("/api/chat")
async def chat(request: ChatRequest):
    try:
        # For now, return a simple response
        # TODO: Integrate with actual AI service
        response_text = f"I received your question: '{request.message}'. This is a placeholder response. The AI integration will be added soon."
        
        return {"response": response_text}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# Document analysis endpoint
@app.post("/api/analyze-document")
async def analyze_document(file: UploadFile = File(...)):
    try:
        # Read file content
        content = await file.read()
        
        # For now, return a simple analysis
        # TODO: Integrate with actual document analysis service
        analysis = f"Document '{file.filename}' uploaded successfully. Size: {len(content)} bytes. Document analysis will be implemented soon."
        
        return {"analysis": analysis}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# Case law search endpoint
@app.post("/api/search-cases")
async def search_cases(request: SearchRequest):
    try:
        # For now, return sample cases
        # TODO: Integrate with actual case law database
        sample_cases = [
            {
                "title": "Sample Case 1 related to: " + request.query,
                "court": "Supreme Court of India",
                "date": "2024-01-15",
                "summary": "This is a sample case result. The actual case law search will be integrated soon.",
                "citation": "AIR 2024 SC 1234"
            },
            {
                "title": "Sample Case 2 related to: " + request.query,
                "court": "Delhi High Court",
                "date": "2023-11-20",
                "summary": "Another sample case for demonstration purposes.",
                "citation": "2023 DHC 5678"
            }
        ]
        
        return {"cases": sample_cases}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# Document generation endpoint
@app.post("/api/generate-document")
async def generate_document(request: DocumentRequest):
    try:
        # For now, return a simple generated document
        # TODO: Integrate with actual document generation service
        document_text = f"""
LEGAL DOCUMENT - {request.document_type.upper()}

Generated by Indian Legal AI
Date: 2024-02-11

Document Type: {request.document_type}

Details Provided:
{request.details}

---
NOTE: This is a placeholder document. The actual AI-powered document generation will be implemented soon.

[Document content will be generated here based on the provided details]
        """
        
        return {"document": document_text.strip()}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
